# Generated by Django 5.2.17 on 2026-10-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pretix_ptinvoicing", "0002_credit_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="issuedinvoice",
            name="document_number",
            field=models.CharField(max_length=64, null=True),
        ),
    ]
