# Generated by Django 5.2.17 on 2026-10-01 21:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pretix_ptinvoicing", "0003_document_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="issuedinvoice",
            name="email_sent",
            field=models.BooleanField(null=True),
        ),
    ]
